stages:
- test
- docker_build

test:
  image: "python:2.7"
  stage: test
  script:
  - apk add --update make
  - make deps
  - make test
docker:
  image: docker:stable
  services:
    - docker:dind
  stage: docker_build
  script:
  - make docker_build

