language: python
services:
- docker
python:
- '2.7'
install:
- make deps
script:
- make test
- make lint
- make docker_push
- make test_xunit
env:
  global:
    secure: OzFjjNx9rtpoJCFQLPwnWYNASIJIE14I8Vg1BJ6SWfpsDQlFwZ1weJQCAJE0ubFcuZpOt9t0TbzvRPSKG1XN8LS+Tzhkz9Zutaaq+d66jQQku5KlSrWum3Z3rT0B6wemFOZfABTUZCfQF26RqdfLGqF/Pp2FmhdGvSPcl732oDFazH1V+yaSyvFsLPfGX+5sWP3+pPaAxB4d/D26aFzRCeGmNaouiCnODo4RLjDBZhVoY3C6VYYbbrLLu2JpQk/Q98dlaaLnj/gqBCezFyIejS/y0KBCpQJI6Myqf/grScgGxXjrUaPWV5qwxZp9B7hmBKmd5ejgii96cRhtHqMPRjns4Zg+o3c2mo8v/gKrklxIjqlfyAGLWhuKRwkQfRSlwVWG2AHgPnDxcs6QsuNtOSCh9+LSt5p9SgojO8GxGwbuvr8jxh4LJczKibf9aS624IMuA01o51ze8+YnNFwYOOBuAhr43P3CCshk92+V0d0kHDfbGBbUvHKGHROAYuRJv1+noGOWzRg6mDXTxibVkCXoECgjbPqrwPijGe4jUNznw52dwxK0pYTwwm3D/yeS25FrnSQOqH1oqwGHDOhBlGunr2MBYEglfoFFAs2N3dXbK/LeHErbc8OMCWEQajvwYB5v8CH1MVLjamBO0sj42qqRctWnrv+yS3oMXn0kUwg=
deploy:
  provider: heroku
  app: dry-fjord-96695
  api_key: ${HEROKU_API_KEY}
